### ISSUE TITLE
[CRITICAL] This does not work on my setup

### ISSUE THREAD

**Issue by Snaipe** [Corwind/termite-install#1]
I just tried to run this script on my old wooden desk by carving the commands, but it seems to be unresponsive. This seems to be an exotic system, where I only have access to echo, a cat, and wine.

[This is my shell.](https://img1.etsystatic.com/007/0/6491016/il_570xN.364948477_oy59.jpg)

I have yet to find a proper way to install termite on this setup and it is critical that I do so in this specific context.

Please advise.

**Comment by Corwind** [comment]
I am sorry to report that your hardware seems to be incompatible with a GNU/Linux environment. Also, your shell is not POSIX compliant. Thus it may be impossible to run this script on your system.

[You should try one of these](http://shots.poussif.eu/three_seashells.jpg), though I have no clue on how to use them.

Thank you for opening this issue, a contribution is always appreciated.
