### ISSUE TITLE
Termite exits upon ctrl+shift+space 

### ISSUE THREAD

**Issue by JanPappert** [Corwind/termite-install#12]
Pretty much title.
Running Ubuntu 16.04 and termite will just close if I try to enter selection mode.

Cheers

**Comment by mmai** [comment]
This pull request solves the problem : https://github.com/Corwind/termite-install/pull/13
You can get the amended script here : https://github.com/kamilwojdylo/termite-install/blob/master/termite-install.sh

**Comment by Corwind** [comment]
I merged #13 so I'm closing this one.
