### ISSUE TITLE
Package vte-2.91 not found

### ISSUE THREAD

**Issue by SRGOM** [Corwind/termite-install#2]

**Comment by SRGOM** [comment]
x

**Comment by Corwind** [comment]
Thanks for the issue, I will test this on a Mint installation by the end of the week and I will update the script.

**Comment by SRGOM** [comment]
I think the following two lines may be good enough till you hear from someone else:
1) After vte install, my vte-2.91.pc was installed in /usr/local/lib/pkgconfig/vte-2.91.pc while my PKG_CONFG_DIR was empty. My makefile says

```
prefix=/usr/local
exec_prefix=$prefix
libdir=${exec_prefix}/lib
pkgconfigdir = ${libdir}/pkgconfig 
```

 So this line should solve this issue: `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH`

2) Also, terminfo is installed in /usr/local/share/terminfo/x/xterm-termite while mint standard terminfo is /lib/terminfo, so mint wants it in /lib/terminfo/x/xterm-termite. So `sudo mkdir -p /lib/terminfo/x; ln -s /usr/local/share/terminfo/x/xterm-termite /lib/terminfo/x/xterm-termite` should help. 
 I understand this is too much hardcoding but I'm not sure how this can be standardized

**Comment by Corwind** [comment]
I tested the script on a Linux Mint based on Ubuntu, it worked well. I only had to use the command you provided to fix terminfo. I will try this on a LMDE.

**Comment by SRGOM** [comment]
I tried it again, and you are right, only the terminal line needs to be added, specifically for mint/ubuntu I think or maybe a check if terminfo installed is in same dir as other terminfos... (by doing a locate terminfo)
