### ISSUE TITLE
'/usr/local/lib/libvte-2.91.so.0.4000.2': No such file or directory

### ISSUE THREAD

**Issue by leninberg** [Corwind/termite-install#6]
Hi!
I couldn't execute your script, so I executed all the lines, one by one
I am running Ubuntu 16.04 64 bits
I have executed these steps:
git clone --recursive https://github.com/thestinger/termite.git
git clone https://github.com/thestinger/vte-ng.git
sudo apt-get install g++ libgtk-3-dev gtk-doc-tools gnutls-bin valac
sudo apt-get install libglib3.0-cil-dev libgnutls28-dev libgirepository1.0-dev
sudo apt-get install libxml2-utils gperf
cd vte-ng && ./autogen.sh && make && sudo make install
cd ../termite && make && sudo make install
sudo cp /usr/local/lib/libvte-2.91.a /usr/local/lib/libvte-2.91.la \
/usr/local/lib/libvte-2.91.so /usr/local/lib/libvte-2.91.so.0 \

I am stuck on this line
/usr/local/lib/libvte-2.91.so.0.4000.2 /usr/lib
after executing that step I get:
cp: cannot stat '/usr/local/lib/libvte-2.91.so.0.4000.2': No such file or directory

Can you give me any advice?
Thanks in advance.

**Comment by tcpaiva** [comment]
@leninberg , you just have to look into the folder `/usr/local/lib/` and find the correct filename (it depends on the vte-ng version of the github repository). In my case I found  `/usr/local/lib/libvte-2.91.so.0.4400.1`.

**Comment by leninberg** [comment]
@tcpaiva, you are right, apparently it changes from what the original script states.
For me it was libvte-2.91.so.0.4400.1 too.
Thanks for the help.
